### ISSUE TITLE
Add starter to new releases

### ISSUE THREAD

**Issue by Nealithh** [Galarzaa90/NabBot#121]
is it possible to add a starter to the new releases like how u did it in 1.2.1 cuz idk how to update them without a windows starter.
like this added in pic.
![screenshot_1](https://user-images.githubusercontent.com/29667671/44178491-f18ed680-a0f2-11e8-8484-50f854adddfe.png)

**Comment by Galarzaa90** [comment]
I removed those because they weren't really universal, Python can be present in your system in many ways (as `py`, `python`, `python3.6`, `python3`), so sometimes it wouldn't work in your system unless you edit it.

You can still use the old ones, they haven't been changed in more than a year, you just need to adjust to however it is in your system.
