### ISSUE TITLE
List players - Hunted

### ISSUE THREAD

**Issue by Fcguedes** [Galarzaa90/NabBot#14]
It would be interesting to create some way to add player to a list, such as hunted or friend.

**Comment by Galarzaa90** [comment]
I'm working on a [rewrite](https://github.com/Galarzaa90/NabBot/tree/rewrite) of NabBot because the library we use (discord.py) is getting rewritten too and it introduces many breaking changes.

So for the moment, development of new features is on halt, only working on bug fixes on the [master branch](https://github.com/Galarzaa90/NabBot/tree/master) while working on getting everything to work again on [rewrite](https://github.com/Galarzaa90/NabBot/tree/rewrite).

**Comment by Galarzaa90** [comment]
This is implemented on the rewrite branch.
