### ISSUE TITLE
distribution?

### ISSUE THREAD

**Issue by Tott3** [Galarzaa90/NabBot#18]
I'm getting this error.
`  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install
`

**Comment by Galarzaa90** [comment]
I made a mistake in the README.md file.

This is the correct command you have to run:

```python -m pip install -U https://github.com/Rapptz/discord.py/archive/master.zip#egg=discord.py[voice] pillow psutil requests```

**Comment by Tott3** [comment]
That solved it. However, running python give egg_info error. Solved it by running python3 instead. Might be good to know if someone else runs into that problem, seems quite a few is doing to on stack overflow.

**Comment by Galarzaa90** [comment]
Maybe `python` in your setup runs Python 2 by default, so you got an error because you didn't meet the requirements for discord.py

The install command varies per person, so I can't specify the exact command for every person (`python3`, `py`, `python`, etc), so I only specify that python 3.4+ is needed, and the user has to run the command according to their setup.
