### ISSUE TITLE
Rewrite - Watched

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#25]
Well.. everything looks fine so far, adding the channel, adding to list, listing..

But it's not "watching".

I guess this might be intentional because it's still in development.
But in case it's not...

**Comment by Galarzaa90** [comment]
What do you mean it's not watching? It takes a bit to scan, but tibia.com's online list doesn't update really fast anyway.

**Comment by fclaussen** [comment]
Well. I added one of my chars to the list. Went online and I've been online for almost 1 hour now and still no notification

**Comment by Galarzaa90** [comment]
Did you create the watched list channel using /watched?

**Comment by fclaussen** [comment]
Yes. and then renamed it to hunted.
Using commands like /watched list work as expected. the bot has write privileges to that channel.

But it doesn't keep track of people actually logging in.

I guess maybe because of this? be1c43fe92b9a1d7f9be61472181c4c51b8fd000

**Comment by Galarzaa90** [comment]
Nope,I reenabled it again in 0fb1853bd20a6a6b1fb4535db887533de867109d

Did you set the tracked world for that server with `/setworld`?

**Comment by fclaussen** [comment]
Yes. It's set to Honbra.

**Comment by Galarzaa90** [comment]
And level and deaths are being announced correctly?

**Comment by fclaussen** [comment]
Level is.
death I haven't tested yet as only me and a couple others are testing it and none of us died yet. I'm considering suiciding my maker today to test it.

**Comment by Galarzaa90** [comment]
If levels are working, deaths should be working. In fact, if /online is
working, watched list should be working too...

Em 16 de jun de 2017 11:39, "Fernando Claussen" <notifications@github.com>
escreveu:

**Comment by fclaussen** [comment]
yea.. that's the weird part.

I believe deaths will work, but since I'm a fellow programmer, I like to test everything to be sure.

But until now, the /watched isn't working for me.

**Comment by fclaussen** [comment]
how frequent the scans happen?

**Comment by fclaussen** [comment]
is it possible for me to enable some debug log so I can check if it prints any errors while trying to watch? That way I can help you with more info

**Comment by fclaussen** [comment]
Deaths worked... kind of.

2017-06-16 20:21:03,013:INFO: Death detected, but too old to announce: Barbie Nutrologa(36) | a vicious squire

**Comment by Galarzaa90** [comment]
That "but too old to announce" is a workaround I made to avoid losing a player's death if the bot went offline or crashed. Every time a character is scanned, his last death will be checked, if it's not saved in the DB yet, it will be added, however, if the death will be announced only if it happened in the last 10 minutes (so NabBot doesn't suddenly announce a 2 day old death).

About having a debug log, there's no debug log, any exception raised would show in the log. But finer debugging would require adding the messages manually (which is why I do when I debug myself, then I remove them before committing)

**Comment by fclaussen** [comment]
I don't know why you closed this. This is not yet resolved.

**Comment by Galarzaa90** [comment]
It had been 15 days and got no reply, so I assumed maybe you fixed it and didn't update it, but we can reopen this.

So, in this watched channel, does this message appear at least?
`There are no watched characters online.`
If it does, does the edited date is recent? Does it keep being updated? If this is true, then we at least know the hunted list part is running. Note that if the list is completely empty, the message wont' be updated.

This is what I did, on a fresh installation of NabBot to test:
- `/setworld Honbra`
- `/watched`
- `/watched add Maxie` - This character was online, so it appeared on the list eventually
- `/watched remove Maxie` - List stopped updating cause it was empty, this is actually something I should change, but this shouldn't be the problem here
- `/watched add Guima Bugadao` - Character was not online, so the list changed to indicate there are no watched characters online. The edit date keeps refreshing every couple minutes
![image](https://user-images.githubusercontent.com/12865379/27771801-79aed230-5f0a-11e7-971e-709151fa91b8.png)

**Comment by fclaussen** [comment]
Oh. That's it!
It is working!
I just though it would send a new message with an alert (@everyone). Just like TS pokes.

I've never checked if the first message was edited and I was sending commands on the channel (which I now understand that I'm not supposed to do).
