### ISSUE TITLE
Announcement Death/Level

### ISSUE THREAD

**Issue by Nealithh** [Galarzaa90/NabBot#27]
Hello, i'm here to ask a question i installed the bot and it's on my server running and all
it does everything except announcing the death/level any idea why?

Greetz, Nealithh

**Comment by Galarzaa90** [comment]
Did you set a world to track using /setworld? And did you register characters?

**Comment by fclaussen** [comment]
This feature works for me. Running the rewrite version

**Comment by diegovicron** [comment]
@Galarzaa90 
I installed the bot and everything was working properly until I tried to create a discord channel specifically for the bot so the general would not be spammed with messages and level ups. After setting up this new channel the bot stopped announcing level ups or deaths. 

I deleted the channel, rolled all permissions back and still the bot is not announcing any level up or death.
The server is correctly set, the chars are still in the bots' "list" but they do not seem to be tracked anymore.

Any idea on what I could do to try to solve the issue?

**Comment by Galarzaa90** [comment]
@diegovicron first of all, are you using **rewrite** or **master**?

If you're on `master`, making the bot not listen to commands on the default channel, but still announce deaths and levels is impossible, cause the only way to do that is to deny read permissions, and that denies write permissions too.

If you're on `rewrite`, you don't need to change permissions, all you have to do is go on a channel and type `/ignore`, and the bot will stop listening to commands in that channel. Deaths and level announcements are done on the channel you set with `/setchannel`, if the channel fails for some reason, it always falls back to using your server's default channel (usually called #general), so if you denied permissions there, it won't announce ever.

**Comment by diegovicron** [comment]
Thanks @Galarzaa90 ! 
I managed to revert the permissions changed by the other administrator and restarted the bot. It seems to be working properly now. 

I will certainly give rewrite a try soon. Any idea on when an stable version will be launched?

**Comment by Galarzaa90** [comment]
@diegovicron 
Rewrite is based on the rewrite branch of [discord.py](https://github.com/Rapptz/discord.py/tree/rewrite/), so when he releases his stable version **1.0.0**, I will "release" the rewrite branch.

This is because breaking changes are still being implemented sometimes, and whenever a breaking change is introduced, I need to update NabBot for it to be compatible again, so someone using it might have trouble with that. So rewrite for now is only recommended for people that have some python knowledge.

Yes, you can run NabBot on more than one server, you just need to repeat the invite part to add it to another server. Once NabBot joined that server, use /setworld there and it will only affect that server.
