### ISSUE TITLE
Dumb question.

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#32]
Is it possible to have the bot running on my computer and have it on multiple servers?

I guess I would need multiple instances of it with the appropriate config.py info and all that, right?

I'm completely ignorant about python, do you have any suggestions on how to keep the bot 24/7 without my computer being on all the time? A server or something?

**Comment by fclaussen** [comment]
Searching google I ended up here: https://wiki.python.org/moin/FreeHosts

do you recommend https://www.pythonanywhere.com/ ?

**Comment by Galarzaa90** [comment]
Yes, it is possible, in fact, that's the way I've been designing it. My instance is running on 4 servers tracking 3 different worlds.

That's why you gotta use /setworld when you install it, cause that sets the world for that server. To add it to another server, just follow the install instructions again, just the part where you [invite the bot to your server](https://github.com/Galarzaa90/NabBot/wiki/Creating-a-Discord-Bot#inviting-your-bot-to-your-server). Note that for it to appear there, you must be the server owner or have **Administrator** permissions.

Other people can use the link to invite your bot if you have the *Public bot* option marked in your application's page.

About keeping it 24/7, I do have a server, a really small one, a Raspberry Pi 2.

I really don't have any recommendations for free hosting, I've been thinking in renting a cheap one.

I'm going to leave this quote from [Discord API's server:](https://discord.gg/discord-api)

-------------

**Need to run your bot 24/7? Get a cheap VPS.**

**Linux hosting:**
https://www.scaleway.com/ - Incredibly cheap but powerful VPSes, owned by https://online.net/, based in Europe.
https://www.digitalocean.com/ - US-based cheap VPSes. The gold standard. Locations available world wide.
https://www.ovh.co.uk/ - Cheap VPSes, used by many people. France and Canadian locations available.
https://www.time4vps.eu/ - Cheap VPSes, seemingly based in Lithuania.
https://www.linode.com/ - More cheap VPSes!
https://www.vultr.com/ - US-based, DigitalOcean-like.

**Windows hosting:**
(To be honest, you should probably just use a linux box.)
https://azure.microsoft.com/en-gb/ - Microsoft-owned. Not on the cheap end, however.

**Others:**
https://aws.amazon.com/ - Amazon Web Services. Free for a year (with certain limits), but very pricey after that.
https://cloud.google.com/compute/ - AWS, but Google.
http://lowendbox.com/ - A curator for lower specced servers.

**Self-hosting:**
You can always self-host on your own hardware. A Raspberry Pi 2 B will be more than sufficient for small to medium sized bots.
For bigger bots, you can build your own server PC for usage, or buy a rack server.
Any modern hardware should work 100% fine.

**Free hosting:**
**No.** There is no good free VPS hoster, outside of persuading somebody to host for you, which is incredibly unlikely.

**Comment by fclaussen** [comment]
I've used digitalocean before. I guess $5 a month is ok. It would be around 17-20 BRL.
I'll see if any of my guild mates want to help me pay for it.
Thanks a lot.
