### ISSUE TITLE
No command called "find" found.

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#58]
## Platform information
* **Operating system:** Ubuntu 17.04
* **Python version:** 3.6.1
* **Repository branch:** rewrite

## Bug information
/find doesn't exist anymore.
looking in the /help it changed to /findteam. /find is not an alias of this command.
It used to work like /find knight,cachero

Looking at /help findteam the description text still mentions /find as the main command. That is no longer true.

**Steps to reproduce:**: /find knight,cachero

**Expected result:** A list of registered users with knights within share range.

**Actual result:** No command called "find" found.

**Comment by fclaussen** [comment]
I understand the nomenclature change. Makes sense.

What I'm saying is that on the Wiki it's /find and on the command help is also /find.
Those should be updated.

**Comment by Galarzaa90** [comment]
@fclaussen the reason for that is because the wiki refers to the master branch. If you check it, you will see that some commands are missing too.

I'm still patiently waiting for discord.py v1.0.0 be released, so I can "release" the rewrite branch too... Then I will update the wiki to reflect all changes made on the rewrite branch.

However, if you find references to /find in the rewrite branch, let me know.

**Comment by Galarzaa90** [comment]
I fixed what the description now.

**Comment by fclaussen** [comment]
👍
