### ISSUE TITLE
Consistent forbidden errors causing bot to be unusable

### ISSUE THREAD

**Issue by Alscara** [Galarzaa90/NabBot#61]
## Platform information
* **Operating system:** Ubuntu 17.04
* **Python version:** 3.5.3
* **Repository branch:** master

## Bug information

Tibia.com returning forbiddens resulting in network errors when using commands

**Steps to reproduce:**: 
Use any command that pings tibia.com for info
**Expected result:**
Command works as intended
**Actual result:**
Bot is borderline unusable because any command that has to ping tibia.com for information fails 80-90% of the time due to receiving consistent forbidden errors from tibia.com

Seems to occur after the bot has been online and actively checking for deaths/levels/highscores, etc. likely being detected as an attack on the web server and being blocked.
No one is spamming the bot or even really using commands very often. Seems to be solely caused by the bot's auto-checking of deaths, levels, highscores, etc. Perhaps checking less often or in a different way could alleviate this? It seems to happen intermittently. It didn't begin happening until after tibia.com and login servers went down a month or two ago. It stopped soon after that, and began again in recent weeks.

Perhaps if the bot just stops actively checking things for a short time upon receiving a forbidden error, and checks only on command for that time?

**Comment by fclaussen** [comment]
This has to do with #51 
I believe @Galarzaa90 is already preparing to make a switch in order to improve that.

The thing is that tibia.com have a "spam protection" feature now. So if you do too many requests it will cause this.
To be honest, I never noticed a problem with this for announcements or commands. But it was annoying when I was manually going to tibia.com to check on something and it failed.

Since I moved it to a VPS this problem went away, but that's not really the same issue you are having.

It's because of tibia.com lack of an api.

The solution here is not checking less often. The solution here would be switching to tibiadata. And as I said, I believe @Galarzaa90 is already preparing for that.

**Comment by Galarzaa90** [comment]
See #64
